### PR TITLE
Updated to 1.0.7 for a cloud bug fix

### PR DESCRIPTION
**Pull request by dy0nysos**
Removed SQL TRIGGER and added dynamic hook on actionObjectCustomerUpdateAfter

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi,

In order to complete the fix, you should remove the trigger creation in the upgrade 1.0.6, and take care to remove the trigger during the upgrade to 1.0.7.

Thanks

**Comment by dy0nysos** [comment]
Hi,

Is it possible that a "DROP TRIGGER IF EXISTS" sql update in the 1.0.7 upgrade triggers the same error than 1.0.6 about trigger restrictions in cloud ?

Should I make it not mandatory to upgrade to this version ?

Thanks

**Comment by Quetzacoalt91** [comment]
Hi @dy0nysos,

You should try directly on a cloud shop to be sure that it works.
On my side, I got an following error during the update to 1.0.7, because of a `$this` written instead of `$object`.

**Comment by dy0nysos** [comment]
Hello @Quetzacoalt91 
I'm not able to upload this updated version on cloud shop.
I fixed the $this instead of $object error.

**Comment by Quetzacoalt91** [comment]
Hi,

Before testing the version 1.0.7, I nned a fix on the upgrade to 1.0.6:
capture du 2015-07-27 10 18 20

You should add a small test in your SQL requests. Something like `CREATE TABLE IF NOT EXIST`.
And in order to fix the previous issue on this upgrade, you should comment the part adding a trigger to the table customers.

**Comment by dy0nysos** [comment]
Hi @Quetzacoalt91 
I tried to handle possible errors in upgrading and downgrading processes.

**Comment by dy0nysos** [comment]
Hi @Quetzacoalt91 

Do you need anything more in order to get this fix merged on master branch ?

Regards

**Comment by Quetzacoalt91** [comment]
Hi @dy0nysos,

Let me test on PrestaShop Cloud and I will tell you ASAP :)

**Comment by Quetzacoalt91** [comment]
capture du 2015-07-28 16 45 55

**Comment by Quetzacoalt91** [comment]
Hi @dy0nysos,

Thanks, the PR has just been merged and the changes will be available from tomorrow.

Best regards

**Pull request merged**
