### PR TITLE
Avoid version compliancy bug on prestashop 1.5.2.0

### PR DESCRIPTION
**Pull request by s4rbacane**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @s4rbacane,

To fix this issue, please comment your PS version compliancy.
On our side, we won't make the module down-loadable on PS < 1.5.0.9

**Comment by s4rbacane** [comment]
Hi, this mean I just have to remove line 45 ?

**Comment by Quetzacoalt91** [comment]
Hi,

You can remove it or comment it, this is our choice. But this line should
not be executed  because of the bug you deal with on this PR

**Comment by s4rbacane** [comment]
Thank you for your comment, I've removed it.

**Comment by Quetzacoalt91** [comment]
Hi @s4rbacane,

Thanks, your PR has just been merged and the changes will be available from tomorrow.

Best regards

**Pull request merged**
